/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RsSideDrawer {
        "close": () => Promise<void>;
        "open": () => Promise<void>;
        "opened": boolean;
        "titulo": string;
    }
}
declare global {
    interface HTMLRsSideDrawerElement extends Components.RsSideDrawer, HTMLStencilElement {
    }
    var HTMLRsSideDrawerElement: {
        prototype: HTMLRsSideDrawerElement;
        new (): HTMLRsSideDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "rs-side-drawer": HTMLRsSideDrawerElement;
    }
}
declare namespace LocalJSX {
    interface RsSideDrawer {
        "opened"?: boolean;
        "titulo"?: string;
    }
    interface IntrinsicElements {
        "rs-side-drawer": RsSideDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rs-side-drawer": LocalJSX.RsSideDrawer & JSXBase.HTMLAttributes<HTMLRsSideDrawerElement>;
        }
    }
}
